// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unicam.Paradigmi.GestoreMusicale.Infrastructure.Persistence.Contexts;

#nullable disable

namespace Unicam.Paradigmi.GestoreMusicale.Infrastructure.Migrations
{
    [DbContext(typeof(GestoreMusicaleContext))]
    partial class GestoreMusicaleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlbumGenere", b =>
                {
                    b.Property<int>("IdAlbum")
                        .HasColumnType("int");

                    b.Property<int>("IdGenere")
                        .HasColumnType("int");

                    b.HasKey("IdAlbum", "IdGenere");

                    b.HasIndex("IdGenere");

                    b.ToTable("AlbumGenere");
                });

            modelBuilder.Entity("Unicam.Paradigmi.GestoreMusicale.Domain.Entities.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlbum"));

                    b.Property<DateTime>("DataUscita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("DescrizioneAlbum");

                    b.Property<int>("IdArtista")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NomeAlbum");

                    b.Property<int>("Prezzo")
                        .HasColumnType("int");

                    b.HasKey("IdAlbum");

                    b.HasIndex("IdArtista");

                    b.ToTable("Albums", (string)null);
                });

            modelBuilder.Entity("Unicam.Paradigmi.GestoreMusicale.Domain.Entities.Artista", b =>
                {
                    b.Property<int>("IdArtista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArtista"));

                    b.Property<string>("NomeArtista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArtista");

                    b.ToTable("Artisti", (string)null);
                });

            modelBuilder.Entity("Unicam.Paradigmi.GestoreMusicale.Domain.Entities.Genere", b =>
                {
                    b.Property<int>("IdGenere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenere"));

                    b.Property<string>("NomeGenere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGenere");

                    b.ToTable("Generi", (string)null);
                });

            modelBuilder.Entity("AlbumGenere", b =>
                {
                    b.HasOne("Unicam.Paradigmi.GestoreMusicale.Domain.Entities.Album", null)
                        .WithMany()
                        .HasForeignKey("IdAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unicam.Paradigmi.GestoreMusicale.Domain.Entities.Genere", null)
                        .WithMany()
                        .HasForeignKey("IdGenere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unicam.Paradigmi.GestoreMusicale.Domain.Entities.Album", b =>
                {
                    b.HasOne("Unicam.Paradigmi.GestoreMusicale.Domain.Entities.Artista", "Artista")
                        .WithMany("Albums")
                        .HasForeignKey("IdArtista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("Unicam.Paradigmi.GestoreMusicale.Domain.Entities.Artista", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
